{
 "title": "New dashboard Copy",
 "time": { "from": "2019-07-11T13:01:39.158Z", "to": "2019-07-17T06:17:37.461Z" },
 "panels": [
  {
   "title": "Flussi totali",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " SELECT flows_as_server+ flows_as_client AS \"total_mibehaving\"FROM \"host:misbehaving_flows\" WHERE(flows_as_client>0 OR flows_as_server>0) AND $timeFilter AND host !~/192.168.1.*/  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Numero flussi anomali",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:anomalous_flows",
     "query": "SELECT flows_as_server+ flows_as_client FROM \"host:misbehaving_flows\" WHERE(flows_as_client>0 OR flows_as_server>0) AND $timeFilter AND host !~/192.168.1.*/  ",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Misbehaving extern host timeline",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"host\",\"flows_as_client\" , \"flows_as_server\"FROM \"host:misbehaving_flows\" WHERE   (\"flows_as_client\">0  OR \"flows_as_server\">0) AND  \"host\"!~/192.168.1.*/ AND \"host\"!='E4:8F:34:CF:4A:E4_v4'   AND \"host\"!='fe80::5f8e:94dd:35d4:e6fd'  AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Misbehaving client flow(extern host)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:misbehaving_flows",
     "query": "SELECT \"flows_as_client\"FROM \"autogen\".\"host:misbehaving_flows\" WHERE (\"host\" !~ /192.168.1.*/ AND \"flows_as_client\" > 0) AND $timeFilter GROUP BY \"host\" fill(null)",
     "select": [
      [
       { "params": [ "flows_as_client" ], "type": "field" }
      ],
      [
       { "params": [ "host" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/192.168.1.*/" },
      { "condition": "AND", "key": "flows_as_client", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Misbehaving server flow(extern host)",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:misbehaving_flows",
     "query": "SELECT \"flows_as_server\" FROM \"autogen\".\"host:misbehaving_flows\" WHERE (\"host\" !~ /192.168.1.*/ AND \"flows_as_server\" > 0) AND $timeFilter GROUP BY \"host\" fill(null)",
     "select": [
      [
       { "params": [ "flows_as_server" ], "type": "field" }
      ],
      [
       { "params": [ "host" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/192.168.1.*/" },
      { "condition": "AND", "key": "flows_as_server", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Misbehaving client flow(local host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"flows_as_client\" FROM \"autogen\".\"host:misbehaving_flows\" WHERE (\"host\" !~ /192.168.1.*/ AND \"flows_as_server\" > 0) AND $timeFilter GROUP BY \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Misbehaving server flow(local host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"flows_as_server\" FROM \"autogen\".\"host:misbehaving_flows\" WHERE (\"host\" =~ /192.168.1.*/ AND \"flows_as_server\" > 0) AND $timeFilter GROUP BY \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "numero pacchetti per tipo di Servizi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "CHAT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Chat" }
     ]
    },
    {
     "alias": "CLOUD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Cloud" }
     ]
    },
    {
     "alias": "COLLABORATIVE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Collaborative" }
     ]
    },
    {
     "alias": "EMAIL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Email" }
     ]
    },
    {
     "alias": "MEDIA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Media" }
     ]
    },
    {
     "alias": "NETWORK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Network" }
     ]
    },
    {
     "alias": "SOCIALNETWORK",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "SocialNetwork" }
     ]
    },
    {
     "alias": "SYSTEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "System" }
     ]
    },
    {
     "alias": "SCONOSCIUTE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Unspecified" }
     ]
    },
    {
     "alias": "VIDEO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Video" }
     ]
    },
    {
     "alias": "VOIP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "VoIP" }
     ]
    },
    {
     "alias": "WEB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "category", "operator": "=", "value": "Web" }
     ]
    }
   ]
  },
  {
   "title": "Pacchetti protocolli livello 4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICMP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:l4protos",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "icmp" }
     ]
    },
    {
     "alias": "IP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:l4protos",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "other_ip" }
     ]
    },
    {
     "alias": "TCP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:l4protos",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "tcp" }
     ]
    },
    {
     "alias": "UDP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:l4protos",
     "query": "SELECT mean(\"bytes\") FROM \"iface:l4protos\" WHERE (\"l4proto\" = 'tcp') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "udp" }
     ]
    }
   ]
  },
  {
   "title": "Pacchetti TCP Host esterni",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Bytes l4 protos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:l4protos",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bytes ndpi_caregories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_categories",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bytes ndpi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "num flow ndpi flows",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi_flows",
     "select": [
      [
       { "params": [ "num_flows" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bytes traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:traffic",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bytes traffix rxtx rcvd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:traffic_rxtx",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "bytes traffix rxtx sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:traffic_rxtx",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:remote2local",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:local2remote",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}